import { agentBackendManager } from "../backend/manager"
import { getServer, publicServer, updateServerHealth, registerServer as registerLegacyServer, updateServer as updateLegacyServer, deleteServer as deleteLegacyServer, type RegisteredServer } from "../server-registry"
import { deletePrimaryBackend, insertPrimaryBackend, isDatabasePrimary, updatePrimaryBackend, updatePrimaryHealth } from "../control-plane/repositories/backend-repository"
import { normalizeBackendEndpoint } from "../backend/network"

export async function listBackendDescriptors() { return agentBackendManager.list() }
export async function getBackend(id: string) { return agentBackendManager.get(id) }
export async function registerBackend(input: { name?: string; baseUrl: string; username?: string; password?: string; enabled?: boolean }) { if (isDatabasePrimary()) { const endpoint = normalizeBackendEndpoint(input.baseUrl); const id = `srv_${crypto.randomUUID()}`; if (!insertPrimaryBackend({ id, name: input.name?.trim() || new URL(endpoint).hostname, endpoint, enabled: input.enabled !== false, username: input.username, password: input.password })) throw new Error("DUPLICATE_SERVER_URL"); return (await listBackendDescriptors()).find((backend) => backend.id === id) } const server = await registerLegacyServer(input); return server }
export async function updateBackend(id: string, input: { name?: string; baseUrl?: string; username?: string; password?: string; enabled?: boolean }) { if (isDatabasePrimary()) { const updated = updatePrimaryBackend(id, { name: input.name, endpoint: input.baseUrl ? normalizeBackendEndpoint(input.baseUrl) : undefined, enabled: input.enabled, username: input.username, password: input.password }); if (!updated) return undefined; await agentBackendManager.invalidate(id); return (await listBackendDescriptors()).find((backend) => backend.id === id) } return updateLegacyServer(id, input) }
export async function deleteBackend(id: string) { if (isDatabasePrimary()) { await agentBackendManager.invalidate(id); return deletePrimaryBackend(id) } return deleteLegacyServer(id) }
export async function probeBackend(id: string, recovery = false) { const health = await agentBackendManager.health(id, recovery); const server = await getServer(id); if (!server) throw new Error("SERVER_NOT_FOUND"); const state: RegisteredServer["state"] = health.healthy ? "READY" : health.authenticated ? "UNHEALTHY" : "AUTH_FAILED"; const update = { state, protocol: health.protocol, reachable: health.reachable, authenticated: health.authenticated, healthy: health.healthy, latencyMs: health.latencyMs, error: health.error as never }; const updated = isDatabasePrimary() ? (updatePrimaryHealth(id, update), await getServer(id)) : await updateServerHealth(id, update); return { server: publicServer(updated || server), health } }
