import { For, Show } from "solid-js"
import type { ContextUsageSnapshot, WorkspaceChange } from "./contracts"

export function ContextIntelligence(props: { usage: () => ContextUsageSnapshot | undefined }) {
  const usage = () => props.usage()
  const percent = () => usage()?.contextLimit && usage()?.contextUsed !== undefined ? Math.min(100, Math.round((usage()!.contextUsed! / usage()!.contextLimit!) * 100)) : undefined
  return <section class="rounded-2xl border border-border-weak-base bg-surface-raised-strong p-4" aria-labelledby="context-intelligence-title"><div class="flex items-start justify-between gap-3"><div><p id="context-intelligence-title" class="text-14-emphasis text-text-strong">Context intelligence</p><p class="text-12-regular text-text-weak">Only values provided by the runtime are shown.</p></div><span class="rounded-full bg-surface-base-hover px-2 py-1 text-11-regular text-text-muted">{percent() === undefined ? "Unknown" : `${percent()}% used`}</span></div><div class="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Model" value={usage()?.model?.modelID ?? "Unavailable"} /><Metric label="Input" value={formatNumber(usage()?.inputTokens)} /><Metric label="Output" value={formatNumber(usage()?.outputTokens)} /><Metric label="Cost" value={usage()?.cost === undefined ? "Unavailable" : usage()!.cost!.toFixed(4)} /></div><Show when={percent() !== undefined}><div class="mt-4 h-1.5 overflow-hidden rounded-full bg-surface-base-hover"><div class="h-full rounded-full bg-icon-info transition-[width]" style={{ width: `${percent()}%` }} /></div></Show></section>
}

function Metric(props: { label: string; value: string }) { return <div class="min-w-0 rounded-xl border border-border-weak-base/70 bg-surface-base px-3 py-2"><p class="text-11-regular text-text-weak">{props.label}</p><p class="mt-1 truncate font-mono text-12-emphasis text-text-strong">{props.value}</p></div> }
function formatNumber(value?: number) { return value === undefined ? "Unavailable" : new Intl.NumberFormat().format(value) }

export function ChangesReviewCenter(props: { changes: () => WorkspaceChange[]; onSelect?: (change: WorkspaceChange) => void }) {
  return <section class="flex min-h-0 flex-col rounded-2xl border border-border-weak-base bg-surface-raised-strong" aria-labelledby="changes-review-title"><header class="flex items-center justify-between gap-3 border-b border-border-weak-base px-4 py-3"><div><p id="changes-review-title" class="text-14-emphasis text-text-strong">Changes & review</p><p class="text-12-regular text-text-weak">Runtime-backed file changes only</p></div><span class="font-mono text-11-regular text-text-muted">{props.changes().length} files</span></header><div class="min-h-0 overflow-auto p-2"><Show when={props.changes().length > 0} fallback={<p class="px-2 py-8 text-center text-12-regular text-text-weak">No changes available.</p>}><For each={props.changes()}>{(change) => <button type="button" class="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-left hover:bg-surface-base-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-border-focus" onClick={() => props.onSelect?.(change)}><span class="shrink-0 rounded-md bg-surface-base-hover px-1.5 py-0.5 font-mono text-11-emphasis text-text-muted">{change.status}</span><span class="min-w-0 flex-1 truncate font-mono text-12-regular text-text-strong">{change.file}</span><span class="shrink-0 font-mono text-11-regular text-text-weak">+{change.additions ?? 0} −{change.deletions ?? 0}</span></button>}</For></Show></div></section>
}
