import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core"

export const AgentBackendsTable = sqliteTable("agent_backends", {
  id: text("id").primaryKey(), type: text("type").notNull(), name: text("name").notNull(), endpoint: text("endpoint").notNull(), enabled: integer("enabled", { mode: "boolean" }).notNull().default(true), state: text("state").notNull(), protocol: text("protocol"), capabilities: text("capabilities", { mode: "json" }).notNull(), configuration: text("configuration", { mode: "json" }), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull(), lastSeenAt: integer("last_seen_at")
}, (table) => ({ endpointUnique: uniqueIndex("agent_backends_endpoint_unique").on(table.endpoint) }))
export const BackendCredentialsTable = sqliteTable("backend_credentials", { backendId: text("backend_id").primaryKey().references(() => AgentBackendsTable.id, { onDelete: "cascade" }), encryptedUsername: text("encrypted_username"), encryptedPassword: text("encrypted_password"), version: integer("version").notNull().default(1), updatedAt: integer("updated_at").notNull() })
export const BackendHealthTable = sqliteTable("backend_health", { backendId: text("backend_id").primaryKey().references(() => AgentBackendsTable.id, { onDelete: "cascade" }), reachable: integer("reachable", { mode: "boolean" }).notNull(), authenticated: integer("authenticated", { mode: "boolean" }).notNull(), healthy: integer("healthy", { mode: "boolean" }).notNull(), latencyMs: integer("latency_ms"), error: text("error"), checkedAt: integer("checked_at").notNull() })
export const PreferencesTable = sqliteTable("preferences", { key: text("key").primaryKey(), value: text("value", { mode: "json" }).notNull(), updatedAt: integer("updated_at").notNull() })
export const WorkspacesTable = sqliteTable("workspaces", { id: text("id").primaryKey(), backendId: text("backend_id").notNull().references(() => AgentBackendsTable.id, { onDelete: "cascade" }), projectId: text("project_id"), agent: text("agent"), providerId: text("provider_id"), modelId: text("model_id"), activeSessionId: text("active_session_id"), createdAt: integer("created_at").notNull(), updatedAt: integer("updated_at").notNull() })
export const SessionIndexTable = sqliteTable("session_index", { backendId: text("backend_id").notNull().references(() => AgentBackendsTable.id, { onDelete: "cascade" }), sessionId: text("session_id").notNull(), projectId: text("project_id"), title: text("title"), updatedAt: integer("updated_at").notNull() })
export const ControlPlaneMetaTable = sqliteTable("control_plane_meta", { key: text("key").primaryKey(), value: text("value").notNull(), updatedAt: integer("updated_at").notNull() })
