import { describe, expect, test } from "bun:test"
import { encryptCredential, decryptCredential } from "../control-plane/encryption/credentials"
import { EventHub } from "./event-hub"
import { CircuitBreaker } from "./circuit-breaker"
import { assertNetworkPolicy, normalizeBackendEndpoint } from "./network"
import { assertImmutableBackendIdentity } from "./domain"

describe("control server foundation", () => {
  test("encrypts credentials with an authenticated versioned payload", () => { const key = Buffer.alloc(32, 7).toString("base64"); const encrypted = encryptCredential("secret", key); expect(encrypted.startsWith("v1.")).toBe(true); expect(decryptCredential(encrypted, key)).toBe("secret"); expect(() => decryptCredential(encrypted, Buffer.alloc(32, 8).toString("base64"))).toThrow() })
  test("normalizes endpoints and rejects URL credentials", () => { expect(normalizeBackendEndpoint("https://example.test///")).toBe("https://example.test"); expect(() => normalizeBackendEndpoint("https://user:pass@example.test")).toThrow("UNSAFE_SERVER_URL") })
  test("rejects private backend destinations by default", () => { expect(() => assertNetworkPolicy("http://127.0.0.1:8080")).toThrow("PRIVATE_NETWORK_NOT_ALLOWED"); expect(() => assertNetworkPolicy("http://169.254.169.254")).toThrow("PRIVATE_NETWORK_NOT_ALLOWED"); expect(assertNetworkPolicy("https://example.test").hostname).toBe("example.test") })
  test("protects immutable backend identity", () => { const identity = { id: "backend-1", type: "opencode" as const }; expect(() => assertImmutableBackendIdentity(identity, { id: "backend-2" })).toThrow("BACKEND_ID_IMMUTABLE"); expect(() => assertImmutableBackendIdentity(identity, { type: "deepseek-harness" })).toThrow("BACKEND_TYPE_IMMUTABLE") })
  test("recovers an open circuit through a privileged probe", () => { const circuit = new CircuitBreaker({ failureThreshold: 1, resetTimeoutMs: 0 }); circuit.failure(true); expect(circuit.canRequest()).toBe(false); expect(circuit.tryRecoveryProbe()).toBe(true); circuit.success(); expect(circuit.canRequest()).toBe(true) })
  test("does not open the circuit for authentication failures", () => { const circuit = new CircuitBreaker({ failureThreshold: 1 }); circuit.failure(false); expect(circuit.snapshot.state).toBe("CLOSED"); expect(circuit.canRequest()).toBe(true) })
  test("permits only one half-open recovery probe", () => { const circuit = new CircuitBreaker({ failureThreshold: 1, resetTimeoutMs: 0, halfOpenMaxProbes: 1 }); circuit.failure(true); expect(circuit.tryRecoveryProbe()).toBe(true); expect(circuit.tryRecoveryProbe()).toBe(false); circuit.failure(true); expect(circuit.snapshot.state).toBe("OPEN") })
  test("tracks and bounds subscribers", async () => { const hub = new EventHub(); const received: string[] = []; hub.subscribe((event) => received.push(event.type), { maxPending: 2, overflow: "coalesce-deltas" }); hub.publish({ id: "1", sequence: 1, backendId: "b", backendType: "opencode", sessionId: "s", type: "MESSAGE_DELTA", timestamp: new Date().toISOString() }); await Promise.resolve(); expect(received).toEqual(["MESSAGE_DELTA"]); expect(hub.metrics().subscribers).toBe(1) })
  test("isolates a slow subscriber from a healthy subscriber and preserves ordering", async () => { const hub = new EventHub(); const slow: string[] = []; const healthy: string[] = []; const slowSub = hub.subscribe((event) => slow.push(event.type), { maxPending: 2, overflow: "coalesce-deltas" }); hub.subscribe((event) => healthy.push(event.type)); for (let sequence = 1; sequence <= 5; sequence++) hub.publish({ id: String(sequence), sequence, backendId: "b", backendType: "opencode", sessionId: "s", type: sequence === 5 ? "MESSAGE_END" : "MESSAGE_DELTA", timestamp: new Date().toISOString() }); await new Promise((resolve) => setTimeout(resolve, 0)); expect(healthy).toEqual(["MESSAGE_DELTA", "MESSAGE_DELTA", "MESSAGE_DELTA", "MESSAGE_DELTA", "MESSAGE_END"]); expect(slowSub.metrics().pending).toBeLessThanOrEqual(2); slowSub.unsubscribe(); expect(hub.metrics().subscribers).toBe(1) })
  test("deduplicates sequence numbers and cleans up listener failures", async () => { const hub = new EventHub(); let calls = 0; const sub = hub.subscribe(() => { calls++; throw new Error("listener failed") }); const event = { id: "1", sequence: 1, backendId: "b", backendType: "opencode" as const, sessionId: "s", type: "MESSAGE_END" as const, timestamp: new Date().toISOString() }; expect(hub.publish(event)).toBe(true); expect(hub.publish({ ...event, id: "duplicate" })).toBe(false); await Promise.resolve(); expect(calls).toBe(1); expect(sub.metrics().disconnected).toBe(true); expect(hub.metrics().subscribers).toBe(0) })
  test("retains critical lifecycle events during noncritical overflow", () => { const hub = new EventHub(); const sub = hub.subscribe(() => undefined, { maxPending: 2, overflow: "disconnect" }); const base = { backendId: "b", backendType: "opencode" as const, sessionId: "s", timestamp: new Date().toISOString() }; hub.publish({ ...base, id: "1", sequence: 1, type: "MESSAGE_DELTA" }); hub.publish({ ...base, id: "2", sequence: 2, type: "MESSAGE_DELTA" }); hub.publish({ ...base, id: "3", sequence: 3, type: "SESSION_IDLE" }); expect(sub.metrics().pending).toBe(2); expect(sub.metrics().disconnected).toBe(false) })
  test("clears sequence state when a backend is disposed", () => { const hub = new EventHub(); const base = { backendId: "b", backendType: "opencode" as const, sessionId: "s", timestamp: new Date().toISOString(), type: "MESSAGE_END" as const }; hub.publish({ ...base, id: "1", sequence: 1 }); expect(hub.metrics().sequences).toBe(1); hub.clearBackend("b"); expect(hub.metrics().sequences).toBe(0) })
})
